return {
[""] = {"", "", "", "",},

["Booma"] = {[0] = "Native", "Booma", "Booma", "Booma", "Bartle"},
["Gobooma"] = {[0] = "Native", "Gobooma", "Gobooma", "Gobooma", "Barble"},
["Gigobooma"] = {[0] = "Native", "Gigobooma", "Gigobooma", "Gigobooma", "Tollaw"},
["Savage Wolf"] = {[0] = "Native", "Savage Wolf", "Savage Wolf", "Savage Wolf", "Gulgus"},
["Barbarous Wolf"] = {[0] = "Native", "Barbarous Wolf", "Barbarous Wolf", "Barbarous Wolf", "Gulgus-Gue"},
["Rag Rappy"] = {[0] = "Native", "Rag Rappy", "Rag Rappy", "Rag Rappy", "El Rappy"},
["Al Rappy"] = {[0] = "Native", "Al Rappy", "Al Rappy", "Al Rappy", "Pal Rappy"},
["Mothmant"] = {[0] = "Native", "Mothmant", "Mothmant", "Mothmant", "Mothvert"},
["Monest"] = {[0] = "Native", "Monest", "Monest", "Monest", "Mothvist"},
["Hildebear"] = {[0] = "Native", "Hildebear", "Hildebear", "Hildebear", "Hildelt"},
["Hildeblue"] = {[0] = "Native", "Hildeblue", "Hildeblue", "Hildeblue", "Hildetorr"},
["Dragon"] = {[0] = "Native", "Dragon", "Dragon", "Dragon", "Sil Dragon"},

["Evil Shark"] = {[0] = "A.Beast", "Evil Shark", "Evil Shark", "Evil Shark", "Vulmer"},
["Pal Shark"] = {[0] = "A.Beast", "Pal Shark", "Pal Shark", "Pal Shark", "Govulmer"},
["Guil Shark"] = {[0] = "A.Beast", "Guil Shark", "Guil Shark", "Guil Shark", "Melqueek"},
["Poison Lily"] = {[0] = "A.Beast", "Poison Lily", "Poison Lily", "Poison Lily", "Ob Lily"},
["Nar Lily"] = {[0] = "A.Beast", "Nar Lily", "Nar Lily", "Nar Lily", "Mil Lily"},
["Pofuilly Slime"] = {[0] = "A.Beast", "Pofuilly Slime", "Pofuilly Slime", "Pofuilly Slime", "Pofuilly Slime"},
["Pouilly Slime"] = {[0] = "A.Beast", "Pouilly Slime", "Pouilly Slime", "Pouilly Slime", "Pouilly Slime"},
["Grass Assassin"] = {[0] = "A.Beast", "Grass Assassin", "Grass Assassin", "Grass Assassin", "Crimson Assassin"},
["Nano Dragon"] = {[0] = "A.Beast", "Nano Dragon", "Nano Dragon", "Nano Dragon", "Nano Dragon"},
["Pan Arms"] = {[0] = "A.Beast", "Pan Arms", "Pan Arms", "Pan Arms", "Pan Arms"},
["Hidoom"] = {[0] = "A.Beast", "Hidoom", "Hidoom", "Hidoom", "Hidoom"},
["Migium"] = {[0] = "A.Beast", "Migium", "Migium", "Migium", "Migium"},
["De Rol Le"] = {[0] = "A.Beast", "De Rol Le", "De Rol Le", "De Rol Le", "Dal Ra Lie"},

["Gillchic"] = {[0] = "Machine", "Gillchic", "Gillchic", "Gillchic", "Gillchich"},
["Dubchic"] = {[0] = "Machine", "Dubchic", "Dubchic", "Dubchic", "Dubchich"},
["Dubwitch"] = {[0] = "None", "Dubwitch", "Dubwitch", "Dubwitch", "Duvuik"},
["Canadine"] = {[0] = "Machine", "Canadine", "Canadine", "Canadine", "Canabin"},
["Canane"] = {[0] = "Machine", "Canane", "Canane", "Canane", "Canune"},
["Sinow Beat"] = {[0] = "Machine", "Sinow Beat", "Sinow Beat", "Sinow Beat", "Sinow Blue"},
["Sinow Gold"] = {[0] = "Machine", "Sinow Gold", "Sinow Gold", "Sinow Gold", "Sinow Red"},
["Garanz"] = {[0] = "Machine", "Garanz", "Garanz", "Garanz", "Baranz"},
["Vol Opt"] = {[0] = "Machine", "Vol Opt", "Vol Opt", "Vol Opt", "Vol Opt ver. 2"},

["Dimenian"] = {[0] = "Dark", "Dimenian", "Dimenian", "Dimenian", "Arlan"},
["La Dimenian"] = {[0] = "Dark", "La Dimenian", "La Dimenian", "La Dimenian", "Merlan"},
["So Dimenian"] = {[0] = "Dark", "So Dimenian", "So Dimenian", "So Dimenian", "Del-D"},
["Claw"] = {[0] = "Dark", "Claw", "Claw", "Claw", "Claw"},
["Bulclaw"] = {[0] = "Dark", "Bulclaw", "Bulclaw", "Bulclaw", "Bulclaw"},
["Bulk"] = {[0] = "Dark", "Bulk", "Bulk", "Bulk", "Bulk"},
["Dark Gunner"] = {[0] = "Dark", "Dark Gunner", "Dark Gunner", "Dark Gunner", "Dark Gunner"},
["Death Gunner"] = {[0] = "Dark", "Death Gunner", "Death Gunner", "Death Gunner", "Death Gunner"},
["Delsaber"] = {[0] = "Dark", "Delsaber", "Delsaber", "Delsaber", "Delsaber"},
["Chaos Sorcerer"] = {[0] = "Dark", "Chaos Sorcerer", "Chaos Sorcerer", "Chaos Sorcerer", "Gran Sorcerer"},
["Dark Belra"] = {[0] = "Dark", "Dark Belra", "Dark Belra", "Dark Belra", "Indi Belra"},
["Chaos Bringer"] = {[0] = "Dark", "Chaos Bringer", "Chaos Bringer", "Chaos Bringer", "Dark Bringer"},
["Dark Falz"] = {[0] = "Dark", "Dark Falz", "Dark Falz", "Dark Falz", "Dark Falz"},

["Dimenian E2"] = {[0] = "Dark", "Dimenian", "Dimenian", "Dimenian", "Arlan"},
["La Dimenian E2"] = {[0] = "Dark", "La Dimenian", "La Dimenian", "La Dimenian", "Merlan"},
["So Dimenian E2"] = {[0] = "Dark", "So Dimenian", "So Dimenian", "So Dimenian", "Del-D"},
["Poison Lily E2"] = {[0] = "A.Beast", "Poison Lily", "Poison Lily", "Poison Lily", "Ob Lily"},
["Nar Lily E2"] = {[0] = "A.Beast", "Nar Lily", "Nar Lily", "Nar Lily", "Mil Lily"},
["Rag Rappy E2"] = {[0] = "Native", "Rag Rappy", "Rag Rappy", "Rag Rappy", "El Rappy"},
["Love Rappy"] = {[0] = "Native", "Love Rappy", "Love Rappy", "Love Rappy", "Love Rappy"},
["St Rappy"] = {[0] = "Native", "St. Rappy", "St. Rappy", "St. Rappy", "St. Rappy"},
["Hallo Rappy"] = {[0] = "Native", "Hallo Rappy", "Hallo Rappy", "Hallo Rappy", "Hallo Rappy"},
["Egg Rappy"] = {[0] = "Native", "Egg Rappy", "Egg Rappy", "Egg Rappy", "Egg Rappy"},
["Mothmant E2"] = {[0] = "Native", "Mothmant", "Mothmant", "Mothmant", "Mothvert"},
["Monest E2"] = {[0] = "Native", "Monest", "Monest", "Monest", "Mothvist"},
["Grass Assassin E2"] = {[0] = "A.Beast", "Grass Assassin", "Grass Assassin", "Grass Assassin", "Crimson Assassin"},
["Hildebear E2"] = {[0] = "Native", "Hildebear", "Hildebear", "Hildebear", "Hildelt"},
["Hildeblue E2"] = {[0] = "Native", "Hildeblue", "Hildeblue", "Hildeblue", "Hildetorr"},
["Dark Belra E2"] = {[0] = "Dark", "Dark Belra", "Dark Belra", "Dark Belra", "Indi Belra"},
["Barba Ray"] = {[0] = "A.Beast", "Barba Ray", "Barba Ray", "Barba Ray", "Barba Ray"},

["Gillchic E2"] = {[0] = "Machine", "Gillchic", "Gillchic", "Gillchic", "Gillchich"},
["Dubchic E2"] = {[0] = "Machine", "Dubchic", "Dubchic", "Dubchic", "Dubchich"},
["Dubwitch E2"] = {[0] = "None", "Dubwitch", "Dubwitch", "Dubwitch", "Duvuik"},
["Savage Wolf E2"] = {[0] = "Native", "Savage Wolf", "Savage Wolf", "Savage Wolf", "Gulgus"},
["Barbarous Wolf E2"] = {[0] = "Native", "Barbarous Wolf", "Barbarous Wolf", "Barbarous Wolf", "Gulgus-Gue"},
["Delsaber E2"] = {[0] = "Dark", "Delsaber", "Delsaber", "Delsaber ", "Delsaber"},
["Chaos Sorcerer E2"] = {[0] = "Dark", "Chaos Sorcerer", "Chaos Sorcerer", "Chaos Sorcerer", "Gran Sorcerer"},
["Garanz E2"] = {[0] = "Machine", "Garanz", "Garanz", "Garanz", "Baranz"},
["Pan Arms E2"] = {[0] = "A.Beast", "Pan Arms", "Pan Arms", "Pan Arms", "Pan Arms"},
["Hidoom E2"] = {[0] = "A.Beast", "Hidoom", "Hidoom", "Hidoom", "Hidoom"},
["Migium E2"] = {[0] = "A.Beast", "Migium", "Migium", "Migium", "Migium"},
["Gol Dragon"] = {[0] = "Native", "Gol Dragon", "Gol Dragon", "Gol Dragon", "Gol Dragon"},

["Merillia"] = {[0] = "A.Beast", "Merillia", "Merillia", "Merillia", "Merillia"},
["Meriltas"] = {[0] = "A.Beast", "Meriltas", "Meriltas", "Meriltas", "Meriltas"},
["Gee"] = {[0] = "Native", "Gee", "Gee", "Gee", "Gee"},
["Ul Gibbon"] = {[0] = "Native", "Ul Gibbon", "Ul Gibbon", "Ul Gibbon", "Ul Gibbon"},
["Zol Gibbon"] = {[0] = "Native", "Zol Gibbon", "Zol Gibbon", "Zol Gibbon", "Zol Gibbon"},
["Sinow Berill"] = {[0] = "Machine", "Sinow Berill", "Sinow Berill", "Sinow Berill", "Sinow Berill"},
["Sinow Spigell"] = {[0] = "Machine", "Sinow Spigell", "Sinow Spigell", "Sinow Spigell", "Sinow Spigell"},
["Gi Gue"] = {[0] = "None", "Gi Gue", "Gi Gue", "Gi Gue", "Gi Gue"},
["Gibbles"] = {[0] = "None", "Gibbles", "Gibbles", "Gibbles", "Gibbles"},
["Mericarol"] = {[0] = "None", "Mericarol", "Mericarol", "Mericarol", "Mericarol"},
["Merikle"] = {[0] = "None", "Merikle", "Merikle", "Merikle", "Merikle"},
["Mericus"] = {[0] = "None", "Mericus", "Mericus", "Mericus", "Mericus"},
["Random Mericarol"] = {[0] = "None", "Mericarand", "Mericarand", "Mericarand", "Mericarand"},
["Gal Gryphon"] = {[0] = "A.Beast", "Gal Gryphon", "Gal Gryphon", "Gal Gryphon", "Gal Gryphon"},

["Dolmolm"] = {[0] = "A.Beast", "Dolmolm", "Dolmolm", "Dolmolm", "Dolmolm"},
["Dolmdarl"] = {[0] = "A.Beast", "Dolmdarl", "Dolmdarl", "Dolmdarl", "Dolmdarl"},
["Recon"] = {[0] = "Machine", "Recon", "Recon", "Recon", "Recon"},
["Recobox"] = {[0] = "Machine", "Recobox", "Recobox", "Recobox", "Recobox"},
["Sinow Zoa"] = {[0] = "Machine", "Sinow Zoa", "Sinow Zoa", "Sinow Zoa", "Sinow Zoa"},
["Sinow Zele"] = {[0] = "Machine", "Sinow Zele", "Sinow Zele", "Sinow Zele", "Sinow Zele"},
["Morfos"] = {[0] = "Dark", "Morfos", "Morfos", "Morfos", "Morfos"},
["Deldepth"] = {[0] = "Dark", "Deldepth", "Deldepth", "Deldepth", "Deldepth"},
["Delbiter"] = {[0] = "Dark", "Delbiter", "Delbiter", "Delbiter", "Delbiter"},
["Olga Flow"] = {[0] = "Dark", "Olga Flow", "Olga Flow", "Olga Flow", "Olga Flow"},

["Del Lily"] = {[0] = "Dark", "Del Lily", "Del Lily", "Del Lily", "Del Lily"},
["Ill Gill"] = {[0] = "Dark", "Ill Gill", "Ill Gill", "Ill Gill", "Ill Gill"},
["Epsilon"] = {[0] = "Machine", "Epsilon", "Epsilon", "Epsilon", "Epsilon"},

["Boota"] = {[0] = "Native", "Boota", "Boota", "Boota", "Boota"},
["Ze Boota"] = {[0] = "Native", "Ze Boota", "Ze Boota", "Ze Boota", "Ze Boota"},
["Ba Boota"] = {[0] = "Native", "Ba Boota", "Ba Boota", "Ba Boota", "Ba Boota"},
["Satellite Lizard"] = {[0] = "Native", "Satellite Lizard", "Satellite Lizard", "Satellite Lizard", "Satellite Lizard"},
["Yowie"] = {[0] = "Native", "Yowie", "Yowie", "Yowie", "Yowie"},
["Sand Rappy"] = {[0] = "Native", "Sand Rappy", "Sand Rappy", "Sand Rappy", "Sand Rappy"},
["Del Rappy"] = {[0] = "Dark", "Del Rappy", "Del Rappy", "Del Rappy", "Del Rappy"},
["Astark"] = {[0] = "A.Beast", "Astark", "Astark", "Astark", "Astark"},
["Zu"] = {[0] = "Native", "Zu", "Zu", "Zu", "Zu"},
["Pazuzu"] = {[0] = "Native", "Pazuzu", "Pazuzu", "Pazuzu", "Pazuzu"},
["Dorphon"] = {[0] = "Native", "Dorphon", "Dorphon", "Dorphon", "Dorphon"},
["Dorphon Eclair"] = {[0] = "Native", "Dorphon Eclair", "Dorphon Eclair", "Dorphon Eclair", "Dorphon Eclair"},

["Goran"] = {[0] = "Dark", "Goran", "Goran", "Goran", "Goran"},
["Pyro Goran"] = {[0] = "Dark", "Pyro Goran", "Pyro Goran", "Pyro Goran", "Pyro Goran"},
["Goran Detonator"] = {[0] = "Dark", "Goran Detonator", "Goran Detonator", "Goran Detonator", "Goran Detonator"},
["Merissa A"] = {[0] = "A.Beast", "Merissa A", "Merissa A", "Merissa A", "Merissa A"},
["Merissa AA"] = {[0] = "A.Beast", "Merissa AA", "Merissa AA", "Merissa AA", "Merissa AA"},
["Girtablulu"] = {[0] = "None", "Girtablulu", "Girtablulu", "Girtablulu", "Girtablulu"},
["Saint Million"] = {[0] = "Dark", "Saint Million", "Saint Million", "Saint Million", "Saint Million"},
["Shambertin"] = {[0] = "Dark", "Shambertin", "Shambertin", "Shambertin", "Shambertin"},
["Kondrieu"] = {[0] = "Dark", "Kondrieu", "Kondrieu", "Kondrieu", "Kondrieu"}
}