return {
[""] = {"", "", "", "",},

["Booma"] = {"Booma", "Booma", "Booma", "Bartle"},
["Gobooma"] = {"Gobooma", "Gobooma", "Gobooma", "Barble"},
["Gigobooma"] = {"Gigobooma", "Gigobooma", "Gigobooma", "Tollaw"},
["Savage Wolf"] = {"Savage Wolf", "Savage Wolf", "Savage Wolf", "Gulgus"},
["Barbarous Wolf"] = {"Barbarous Wolf", "Barbarous Wolf", "Barbarous Wolf", "Gulgus-Gue"},
["Rag Rappy"] = {"Rag Rappy", "Rag Rappy", "Rag Rappy", "El Rappy"},
["Al Rappy"] = {"Al Rappy", "Al Rappy", "Al Rappy", "Pal Rappy"},
["Mothmant"] = {"Mothmant", "Mothmant", "Mothmant", "Mothvert"},
["Monest"] = {"Monest", "Monest", "Monest", "Mothvist"},
["Hildebear"] = {"Hildebear", "Hildebear", "Hildebear", "Hildelt"},
["Hildeblue"] = {"Hildeblue", "Hildeblue", "Hildeblue", "Hildetorr"},
["Dragon"] = {"Dragon", "Dragon", "Dragon", "Sil Dragon"},

["Evil Shark"] = {"Evil Shark", "Evil Shark", "Evil Shark", "Vulmer"},
["Pal Shark"] = {"Pal Shark", "Pal Shark", "Pal Shark", "Govulmer"},
["Guil Shark"] = {"Guil Shark", "Guil Shark", "Guil Shark", "Melqueek"},
["Poison Lily"] = {"Poison Lily", "Poison Lily", "Poison Lily", "Ob Lily"},
["Nar Lily"] = {"Nar Lily", "Nar Lily", "Nar Lily", "Mil Lily"},
["Pofuilly Slime"] = {"Pofuilly Slime", "Pofuilly Slime", "Pofuilly Slime", "Pofuilly Slime"},
["Pouilly Slime"] = {"Pouilly Slime", "Pouilly Slime", "Pouilly Slime", "Pouilly Slime"},
["Grass Assassin"] = {"Grass Assassin", "Grass Assassin", "Grass Assassin", "Crimson Assassin"},
["Nano Dragon"] = {"Nano Dragon", "Nano Dragon", "Nano Dragon", "Nano Dragon"},
["Pan Arms"] = {"Pan Arms", "Pan Arms", "Pan Arms", "Pan Arms"},
["Hidoom"] = {"Hidoom", "Hidoom", "Hidoom", "Hidoom"},
["Migium"] = {"Migium", "Migium", "Migium", "Migium"},
["De Rol Le"] = {"De Rol Le", "De Rol Le", "De Rol Le", "Dal Ra Lie"},

["Gillchic"] = {"Gillchic", "Gillchic", "Gillchic", "Gillchich"},
["Dubchic"] = {"Dubchic", "Dubchic", "Dubchic", "Dubchich"},
["Dubwitch"] = {"Dubwitch", "Dubwitch", "Dubwitch", "Duvuik"},
["Canadine"] = {"Canadine", "Canadine", "Canadine", "Canabin"},
["Canane"] = {"Canane", "Canane", "Canane", "Canune"},
["Sinow Beat"] = {"Sinow Beat", "Sinow Beat", "Sinow Beat", "Sinow Blue"},
["Sinow Gold"] = {"Sinow Gold", "Sinow Gold", "Sinow Gold", "Sinow Red"},
["Garanz"] = {"Garanz", "Garanz", "Garanz", "Baranz"},
["Vol Opt"] = {"Vol Opt", "Vol Opt", "Vol Opt", "Vol Opt ver. 2"},

["Dimenian"] = {"Dimenian", "Dimenian", "Dimenian", "Arlan"},
["La Dimenian"] = {"La Dimenian", "La Dimenian", "La Dimenian", "Merlan"},
["So Dimenian"] = {"So Dimenian", "So Dimenian", "So Dimenian", "Del-D"},
["Claw"] = {"Claw", "Claw", "Claw", "Claw"},
["Bulclaw"] = {"Bulclaw", "Bulclaw", "Bulclaw", "Bulclaw"},
["Bulk"] = {"Bulk", "Bulk", "Bulk", "Bulk"},
["Dark Gunner"] = {"Dark Gunner", "Dark Gunner", "Dark Gunner", "Dark Gunner"},
["Death Gunner"] = {"Death Gunner", "Death Gunner", "Death Gunner", "Death Gunner"},
["Delsaber"] = {"Delsaber", "Delsaber", "Delsaber", "Delsaber"},
["Chaos Sorcerer"] = {"Chaos Sorcerer", "Chaos Sorcerer", "Chaos Sorcerer", "Gran Sorcerer"},
["Dark Belra"] = {"Dark Belra", "Dark Belra", "Dark Belra", "Indi Belra"},
["Chaos Bringer"] = {"Chaos Bringer", "Chaos Bringer", "Chaos Bringer", "Dark Bringer"},
["Dark Falz"] = {"Dark Falz", "Dark Falz", "Dark Falz", "Dark Falz"},

["Dimenian E2"] = {"Dimenian", "Dimenian", "Dimenian", "Arlan"},
["La Dimenian E2"] = {"La Dimenian", "La Dimenian", "La Dimenian", "Merlan"},
["So Dimenian E2"] = {"So Dimenian", "So Dimenian", "So Dimenian", "Del-D"},
["Poison Lily E2"] = {"Poison Lily", "Poison Lily", "Poison Lily", "Ob Lily"},
["Nar Lily E2"] = {"Nar Lily", "Nar Lily", "Nar Lily", "Mil Lily"},
["Rag Rappy E2"] = {"Rag Rappy", "Rag Rappy", "Rag Rappy", "El Rappy"},
["Love Rappy"] = {"Love Rappy", "Love Rappy", "Love Rappy", "Love Rappy"},
["St Rappy"] = {"St. Rappy", "St. Rappy", "St. Rappy", "St. Rappy"},
["Hallo Rappy"] = {"Hallo Rappy", "Hallo Rappy", "Hallo Rappy", "Hallo Rappy"},
["Egg Rappy"] = {"Egg Rappy", "Egg Rappy", "Egg Rappy", "Egg Rappy"},
["Mothmant E2"] = {"Mothmant", "Mothmant", "Mothmant", "Mothvert"},
["Monest E2"] = {"Monest", "Monest", "Monest", "Mothvist"},
["Grass Assassin E2"] = {"Grass Assassin", "Grass Assassin", "Grass Assassin", "Crimson Assassin"},
["Hildebear E2"] = {"Hildebear", "Hildebear", "Hildebear", "Hildelt"},
["Hildeblue E2"] = {"Hildeblue", "Hildeblue", "Hildeblue", "Hildetorr"},
["Dark Belra E2"] = {"Dark Belra", "Dark Belra", "Dark Belra", "Indi Belra"},
["Barba Ray"] = {"Barba Ray", "Barba Ray", "Barba Ray", "Barba Ray"},

["Gillchic E2"] = {"Gillchic", "Gillchic", "Gillchic", "Gillchich"},
["Dubchic E2"] = {"Dubchic", "Dubchic", "Dubchic", "Dubchich"},
["Dubwitch E2"] = {"Dubwitch", "Dubwitch", "Dubwitch", "Duvuik"},
["Savage Wolf E2"] = {"Savage Wolf", "Savage Wolf", "Savage Wolf", "Gulgus"},
["Barbarous Wolf E2"] = {"Barbarous Wolf", "Barbarous Wolf", "Barbarous Wolf", "Gulgus-Gue"},
["Delsaber E2"] = {"Delsaber", "Delsaber", "Delsaber ", "Delsaber"},
["Chaos Sorcerer E2"] = {"Chaos Sorcerer", "Chaos Sorcerer", "Chaos Sorcerer", "Gran Sorcerer"},
["Garanz E2"] = {"Garanz", "Garanz", "Garanz", "Baranz"},
["Pan Arms E2"] = {"Pan Arms", "Pan Arms", "Pan Arms", "Pan Arms"},
["Hidoom E2"] = {"Hidoom", "Hidoom", "Hidoom", "Hidoom"},
["Migium E2"] = {"Migium", "Migium", "Migium", "Migium"},
["Gol Dragon"] = {"Gol Dragon", "Gol Dragon", "Gol Dragon", "Gol Dragon"},

["Merillia"] = {"Merillia", "Merillia", "Merillia", "Merillia"},
["Meriltas"] = {"Meriltas", "Meriltas", "Meriltas", "Meriltas"},
["Gee"] = {"Gee", "Gee", "Gee", "Gee"},
["Ul Gibbon"] = {"Ul Gibbon", "Ul Gibbon", "Ul Gibbon", "Ul Gibbon"},
["Zol Gibbon"] = {"Zol Gibbon", "Zol Gibbon", "Zol Gibbon", "Zol Gibbon"},
["Sinow Berill"] = {"Sinow Berill", "Sinow Berill", "Sinow Berill", "Sinow Berill"},
["Sinow Spigell"] = {"Sinow Spigell", "Sinow Spigell", "Sinow Spigell", "Sinow Spigell"},
["Gi Gue"] = {"Gi Gue", "Gi Gue", "Gi Gue", "Gi Gue"},
["Gibbles"] = {"Gibbles", "Gibbles", "Gibbles", "Gibbles"},
["Mericarol"] = {"Mericarol", "Mericarol", "Mericarol", "Mericarol"},
["Merikle"] = {"Merikle", "Merikle", "Merikle", "Merikle"},
["Mericus"] = {"Mericus", "Mericus", "Mericus", "Mericus"},
["Random Mericarol"] = {"Mericarand", "Mericarand", "Mericarand", "Mericarand"},
["Gal Gryphon"] = {"Gal Gryphon", "Gal Gryphon", "Gal Gryphon", "Gal Gryphon"},

["Dolmolm"] = {"Dolmolm", "Dolmolm", "Dolmolm", "Dolmolm"},
["Dolmdarl"] = {"Dolmdarl", "Dolmdarl", "Dolmdarl", "Dolmdarl"},
["Recon"] = {"Recon", "Recon", "Recon", "Recon"},
["Recobox"] = {"Recobox", "Recobox", "Recobox", "Recobox"},
["Sinow Zoa"] = {"Sinow Zoa", "Sinow Zoa", "Sinow Zoa", "Sinow Zoa"},
["Sinow Zele"] = {"Sinow Zele", "Sinow Zele", "Sinow Zele", "Sinow Zele"},
["Morfos"] = {"Morfos", "Morfos", "Morfos", "Morfos"},
["Deldepth"] = {"Deldepth", "Deldepth", "Deldepth", "Deldepth"},
["Delbiter"] = {"Delbiter", "Delbiter", "Delbiter", "Delbiter"},
["Olga Flow"] = {"Olga Flow", "Olga Flow", "Olga Flow", "Olga Flow"},

["Del Lily"] = {"Del Lily", "Del Lily", "Del Lily", "Del Lily"},
["Ill Gill"] = {"Ill Gill", "Ill Gill", "Ill Gill", "Ill Gill"},
["Epsilon"] = {"Epsilon", "Epsilon", "Epsilon", "Epsilon"},

["Boota"] = {"Boota", "Boota", "Boota", "Boota"},
["Ze Boota"] = {"Ze Boota", "Ze Boota", "Ze Boota", "Ze Boota"},
["Ba Boota"] = {"Ba Boota", "Ba Boota", "Ba Boota", "Ba Boota"},
["Satellite Lizard"] = {"Satellite Lizard", "Satellite Lizard", "Satellite Lizard", "Satellite Lizard"},
["Yowie"] = {"Yowie", "Yowie", "Yowie", "Yowie"},
["Sand Rappy"] = {"Sand Rappy", "Sand Rappy", "Sand Rappy", "Sand Rappy"},
["Del Rappy"] = {"Del Rappy", "Del Rappy", "Del Rappy", "Del Rappy"},
["Astark"] = {"Astark", "Astark", "Astark", "Astark"},
["Zu"] = {"Zu", "Zu", "Zu", "Zu"},
["Pazuzu"] = {"Pazuzu", "Pazuzu", "Pazuzu", "Pazuzu"},
["Dorphon"] = {"Dorphon", "Dorphon", "Dorphon", "Dorphon"},
["Dorphon Eclair"] = {"Dorphon Eclair", "Dorphon Eclair", "Dorphon Eclair", "Dorphon Eclair"},

["Goran"] = {"Goran", "Goran", "Goran", "Goran"},
["Pyro Goran"] = {"Pyro Goran", "Pyro Goran", "Pyro Goran", "Pyro Goran"},
["Goran Detonator"] = {"Goran Detonator", "Goran Detonator", "Goran Detonator", "Goran Detonator"},
["Merissa A"] = {"Merissa A", "Merissa A", "Merissa A", "Merissa A"},
["Merissa AA"] = {"Merissa AA", "Merissa AA", "Merissa AA", "Merissa AA"},
["Girtablulu"] = {"Girtablulu", "Girtablulu", "Girtablulu", "Girtablulu"},
["Saint Million"] = {"Saint Million", "Saint Million", "Saint Million", "Saint Million"},
["Shambertin"] = {"Shambertin", "Shambertin", "Shambertin", "Shambertin"},
["Kondrieu"] = {"Kondrieu", "Kondrieu", "Kondrieu", "Kondrieu"}
}