return {
[""] = {"", "", "", ""},

["Booma"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Gobooma"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Gigobooma"] = {"Barrier", "Barrier", "Unit", "Unit"},
["Savage Wolf"] = {"Frame", "Frame", "Frame", "Frame"},
["Barbarous Wolf"] = {"Weapon", "Weapon", "Barrier", "Barrier"},
["Rag Rappy"] = {"Frame", "Frame", "Barrier", "Barrier"},
["Al Rappy"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Mothmant"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Monest"] = {"None", "None", "None", "None"},
["Hildebear"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Hildeblue"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dragon"] = {"None", "None", "None", "None"},

["Evil Shark"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Pal Shark"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Guil Shark"] = {"Unit", "Unit", "Unit", "Unit"},
["Poison Lily"] = {"Frame", "Frame", "Frame", "Frame"},
["Nar Lily"] = {"Unit", "Unit", "Unit", "Unit"},
["Pofuilly Slime"] = {"Frame", "Frame", "Frame", "Frame"},
["Pouilly Slime"] = {"Unit", "Unit", "Unit", "Unit"},
["Grass Assassin"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Nano Dragon"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Pan Arms"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Hidoom"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Migium"] = {"Unit", "Unit", "Unit", "Unit"},
["De Rol Le"] = {"None", "None", "None", "None"},

["Gillchic"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dubchic"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dubwitch"] = {"None", "None", "None", "None"},
["Canadine"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Canane"] = {"Frame", "Frame", "Frame", "Frame"},
["Sinow Beat"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Sinow Gold"] = {"Unit", "Unit", "Unit", "Unit"},
["Garanz"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Vol Opt"] = {"None", "None", "None", "None"},

["Dimenian"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["La Dimenian"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["So Dimenian"] = {"Frame", "Frame", "Frame", "Frame"},
["Claw"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Bulclaw"] = {"Unit", "Unit", "Unit", "Unit"},
["Bulk"] = {"Unit", "Unit", "Unit", "Unit"},
["Dark Gunner"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Death Gunner"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Delsaber"] = {"Frame", "Frame", "Frame", "Frame"},
["Chaos Sorcerer"] = {"Unit", "Unit", "Unit", "Unit"},
["Dark Belra"] = {"Frame", "Frame", "Frame", "Frame"},
["Chaos Bringer"] = {"Unit", "Unit", "Unit", "Unit"},
["Dark Falz"] = {"None", "None", "None", "None"},

["Dimenian E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["La Dimenian E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["So Dimenian E2"] = {"Frame", "Frame", "Frame", "Frame"},
["Poison Lily E2"] = {"Frame", "Frame", "Frame", "Frame"},
["Nar Lily E2"] = {"Unit", "Unit", "Unit", "Unit"},
["Rag Rappy E2"] = {"Frame", "Frame", "Barrier", "Barrier"},
["Love Rappy"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["St Rappy"] = {"None", "None", "None", "None"},
["Hallo Rappy"] = {"None", "None", "None", "None"},
["Egg Rappy"] = {"None", "None", "None", "None"},
["Mothmant E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Monest E2"] = {"None", "None", "None", "None"},
["Grass Assassin E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Hildebear E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Hildeblue E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dark Belra E2"] = {"Frame", "Frame", "Frame", "Frame"},
["Barba Ray"] = {"None", "None", "None", "None"},

["Gillchic E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dubchic E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dubwitch E2"] = {"None", "None", "None", "None"},
["Savage Wolf E2"] = {"Frame", "Frame", "Frame", "Frame"},
["Barbarous Wolf E2"] = {"Weapon", "Weapon", "Barrier", "Barrier"},
["Delsaber E2"] = {"Frame", "Frame", "Frame", "Frame"},
["Chaos Sorcerer E2"] = {"Unit", "Unit", "Unit", "Unit"},
["Garanz E2"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Pan Arms E2"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Hidoom E2"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Migium E2"] = {"Unit", "Unit", "Unit", "Unit"},
["Gol Dragon"] = {"None", "None", "None", "None"},

["Merillia"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Meriltas"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Gee"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Ul Gibbon"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Zol Gibbon"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Sinow Berill"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Sinow Spigell"] = {"Frame", "Frame", "Frame", "Frame"},
["Gi Gue"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Gibbles"] = {"Unit", "Unit", "Unit", "Unit"},
["Mericarol"] = {"Unit", "Unit", "Unit", "Unit"},
["Merikle"] = {"Frame", "Frame", "Frame", "Frame"},
["Mericus"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Random Mericarol"] = {"", "", "", ""},
["Gal Gryphon"] = {"None", "None", "None", "None"},

["Dolmolm"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dolmdarl"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Recon"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Recobox"] = {"Unit", "Unit", "Unit", "Unit"},
["Sinow Zoa"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Sinow Zele"] = {"Frame", "Frame", "Frame", "Frame"},
["Morfos"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Deldepth"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Delbiter"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Olga Flow"] = {"None", "None", "None", "None"},

["Del Lily"] = {"Frame", "Frame", "Frame", "Frame"},
["Ill Gill"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Epsilon"] = {"Unit", "Unit", "Unit", "Unit"},

["Boota"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Ze Boota"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Ba Boota"] = {"Barrier", "Barrier", "Unit", "Unit"},
["Satellite Lizard"] = {"Frame", "Frame", "Frame", "Frame"},
["Yowie"] = {"Weapon", "Weapon", "Barrier", "Barrier"},
["Sand Rappy"] = {"Frame", "Frame", "Barrier", "Barrier"},
["Del Rappy"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Astark"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Zu"] = {"Barrier", "Barrier", "Barrier", "Barrier"},
["Pazuzu"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dorphon"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Dorphon Eclair"] = {"Weapon", "Weapon", "Weapon", "Weapon"},

["Goran"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Pyro Goran"] = {"Weapon", "Weapon", "Weapon", "Weapon"},
["Goran Detonator"] = {"Frame", "Frame", "Frame", "Frame"},
["Merissa A"] = {"Frame", "Frame", "Frame", "Frame"},
["Merissa AA"] = {"Unit", "Unit", "Unit", "Unit"},
["Girtablulu"] = {"Unit", "Unit", "Unit", "Unit"},
["Saint Million"] = {"None", "None", "None", "None"},
["Shambertin"] = {"None", "None", "None", "None"},
["Kondrieu"] = {"None", "None", "None", "None"},
}